-- 코드를 입력하세요
SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) AS 전화번호 -- CONCAT()은 집계함수가 아닌 컬럼(단순 문자열 함수)임
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER
    ON WRITER_ID = USER_ID
GROUP BY USER_ID, NICKNAME, 전체주소, 전화번호
HAVING COUNT(NICKNAME) >= 3
ORDER BY USER_ID DESC;