-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%' -- 부분 문자열 비교는 LIKE + %
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%'
         OR SEX_UPON_OUTCOME LIKE 'Neutered%') -- 여러 조건은 OR로 연결
ORDER BY O.ANIMAL_ID;
