-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = ( -- WHERE 절은 행단위 조건을 검사하므로, 서브쿼리로 MAX(PRICE) 먼저 구해야 함
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
);