-- 한쪽엔 있는데 다른쪽엔 없는 데이터 찾기
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I -- OUTS에는 있고, INS에는 없는 ANIMAL_ID 찾기 (NAME까지 없어도 됨)
    ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;