-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
    ON F.FISH_TYPE = N.FISH_TYPE
GROUP BY N.FISH_NAME -- SELECT에 없는 컬럼을 쓰려면 1:1 대응이어야 하고, 출력값에 있는 컬럼으로 쓰는게 더 명확
ORDER BY FISH_COUNT DESC;