-- 코드를 입력하세요
WITH HOURS AS ( -- WITH절은 SELECT, INSERT, UPDATE, DELETE 앞에 와야 함 (이 쿼리에서 미리 쓸 임시 테이블 정의하는 부분, 그 쿼리 안에서만 유효하고 WITH 블록 밖에서는 사라짐, 한 문장단 한 번만 맨 위에서 정의)
    SELECT 0 AS HOUR UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3
    UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7
    UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11
    UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
    UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23
)
SELECT
    H.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT
FROM HOURS AS H
LEFT JOIN ANIMAL_OUTS AS O
    ON H.HOUR = HOUR(O.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;